### PR TITLE
Merge all hot fix PR's back to master branch

### PR DESCRIPTION
**Pull request by bcyan**

### CODE REVIEW

**Comment by bcyan** [comment]
@fub2 @weia5-emc @JuneZhou19 @xiar @chenge3 @chenc52 @turtle-fly @XiaowenJiang

**Comment by turtle-fly** [comment]
@bcyan , try to make a PR from infrasim-3.5 branch to master branch.
It will make more sense than PR from your master to official master.

**Comment by turtle-fly** [comment]
comment again...I'm OK to this PR because it will make the same commit network graph as expected release branch strategy.

**Comment by bcyan** [comment]
@fub2 @weia5-emc @JuneZhou19 @xiar @turtle-fly @chenc52 @chenge3 @XiaowenJiang

**Pull request merged**
