### PR TITLE
Forward docker container port to host upon docker run.

### PR DESCRIPTION
**Pull request by JuneZhou19**
@InfraSIM/infrasim_dev

### CODE REVIEW

**Comment by chenge3** [comment]
👍

**Comment by JuneZhou19** [comment]
@fub2 @turtle-fly @XiaowenJiang

**Comment by JuneZhou19** [comment]
The PR is also covered in another PR just created.

**Comment by JuneZhou19** [comment]
The PR is also covered in another PR just created.

**Pull request closed without merging**
