### PR TITLE
Added emu_parser utility

### PR DESCRIPTION
**Pull request by turtle-fly**
fru_data_operation.py
- Read/Write emu_data_file
- Get FRU data add command
- Example to read/write fru data

fru_model.py
- Organize area
- Orgniaze field
- Read/Write capability to each field

### CODE REVIEW

**Comment by turtle-fly** [comment]
@xiar @fub2 @MarkMa001 @PaynePei @JuneZhou19 @XiaowenJiang

**Comment by fub2** [comment]
[minor]folder named with "emu_parser"; how about being more specific, probably fru_data_utility?

**Comment by turtle-fly** [comment]
@fub2 considering further operation on other emu data management. 
e.g. Sensor number and initial reading value management.

But currently it's better to be fru_data_utility, updated.

**Comment by turtle-fly** [comment]
这道菜下了两天了，再不出锅就老了～
@xiar @MarkMa001 @PaynePei @fub2 @JiangxiaoWeng @JuneZhou19

**Comment by fub2** [comment]
+1

**Comment by sharkconi** [comment]
+1

**Pull request merged**
