### PR TITLE
Add ansible playbook for scale control

### PR DESCRIPTION
**Pull request by XiaowenJiang**
Create a playbook to control multiple hosts in one command.
There are five roles in the playbook:
* installation: steps to install infrasim-compute on a pure ubuntu
16.04.

* uninstallation: pip uninstall infrasim-compute.

* commoncmd: including commands infrasim version/init/help.

* configcmd: including commands infrasim config add/delete/update and modification of node type.

* nodecmd: including commands infrasim node
start/stop/restart/destroy/status/info.

### CODE REVIEW

**Comment by turtle-fly** [comment]
++

**Comment by XiaowenJiang** [comment]
@xiar @fub2 @turtle-fly @chenge3 Have a try~

**Comment by JuneZhou19** [comment]
To let people know the version of ansible should be 2.2 or newer.

**Comment by JuneZhou19** [comment]
In readme file, is below sentence complete?
"l limits hosts by specified pattern, if omitted, "

**Comment by JuneZhou19** [comment]
Can we also need infrasim uninstall command similiar to "sudo pip uninstall infrasim-compute" in node?

**Comment by JuneZhou19** [comment]
Can readme add a hint for user to edit inventory_example.yml between appropriate steps?

**Comment by JuneZhou19** [comment]
Can readme add a hint for user to edit inventory_example between appropriate steps?

**Comment by fub2** [comment]
--Not sure about it. should we be covering basic concept of usage on Ansible?

**Comment by XiaowenJiang** [comment]
@JuneZhou19 @fub2  I'll add an ansible inventory doc link in readme and specify the meaning of sub-groups. 
What June concerns is that after "infrasim init", all infrasims under different groups of hosts are still "quanta_d51", which might confuse users like "why I specify this 192.xx.xx.xx to be dell but it's quanta?". Additional instructions are needed in readme.

**Comment by fub2** [comment]
Is this good to go? Going to merge it.

**Comment by fub2** [comment]
my +1

**Comment by JuneZhou19** [comment]
+1

**Pull request merged**
