### PR TITLE
udpate deb install scripts for qemu and openipmi:

### PR DESCRIPTION
**Pull request by PaynePei**
change the install path of qemu and openipmi to "/usr/local/bin/"

### CODE REVIEW

**Comment by PaynePei** [comment]
@fub2 @xiar @MarkMa001 @JuneZhou19 @turtle-fly @XiaowenJiang please help review

**Comment by sharkconi** [comment]
+1

**Comment by fub2** [comment]
+1

**Comment by JuneZhou19** [comment]
+1

**Pull request merged**
